name: Publish nightly build

on:
  push:
    branches:
      - main
      - ci-nightly-test

jobs:
  nightly:
    name: Publish nightly build
    runs-on: ubuntu-latest
    environment: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '!onionshare-android/fdroid') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build
        run: ./gradlew assembleNightlyDebug
      - name: F-Droid nightly builds
        uses: wardvl/f-droid-nightly-action@v2.1
        with:
          debug_keystore: ${{ secrets.DEBUG_KEYSTORE }}
          fdroid_nightly_args: --archive-older 10
